Algoritmo "fatorial"

Var

   f, n, c : inteiro
   r : caractere

Inicio

r <- "s"
Repita
      Escreva ("Dgite um numero: ")
      Leia (N)
      C <- n
      F <- 1
      Repita
            F <- f * c
            c <- c - 1
      Ate (C < 1)
      Escreval ("O valor do fatorial de ", n, " e igual a ", f)
      Escreva ("Você quer continuar [S/N]? ")
      Leia (r)
      limpatela
Ate (r = "n")


Fimalgoritmo